#!/usr/bin/env node
// 构建 client.js：rolldown 把 src/client-entry.ts 打包为 CJS（react 外部化），
// 再包进 window.__ModuleLoader__.load({ id, factory }) 外壳（danger-guard 同款）。
// id 取 package.json 的 name，与 dsh.client 模块表键一致。
// 运行：node build-client.mjs（或 npm run build:client）。buildClient() 供测试导入。
/// <reference types="node" />
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { rolldown } from "rolldown";
import { canonicalizeRegionPaths } from "@jayyuen666/dsh-plugin-shared/lib/canonicalize-region-paths";

const root = import.meta.dirname;

/** 从 JSON.parse 的 unknown 投影为 Record（非对象 → 空对象兜底），避免 any 索引。
 *  @param {unknown} raw
 *  @returns {Record<string, unknown>}
 */
function asRecord(raw) {
  if (raw !== null && typeof raw === "object" && !Array.isArray(raw)) {
    return raw;
  }
  return {};
}

/** 生成 client.js 的完整文本（含 ModuleLoader 外壳）。 */
export async function buildClient() {
  /** @type {unknown} */
  const pkgJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));
  const nameKey = "name";
  const pkgNameRaw = asRecord(pkgJson)[nameKey];
  const pkgName = typeof pkgNameRaw === "string" ? pkgNameRaw : "unknown";
  const bundle = await rolldown({
    input: path.join(root, "src", "client-entry.ts"),
    external: ["react"],
    platform: "browser",
    resolve: {
      extensions: [".ts", ".mjs", ".js", ".json"],
    },
  });
  const { output } = await bundle.generate({
    format: "cjs",
  });
  const chunk = output.find((item) => item.type === "chunk");
  if (chunk === undefined) {
    throw new Error("rolldown generate returned no chunk output");
  }
  // 见 shared/lib/canonicalize-region-paths.ts：`//#region` 行的路径由 rolldown 按 process.cwd()
  // 算出 ⇒ 同一份源码两种字节。折 canonical 必须落在返回值之前（test/client-freshness.ts 逐字节
  // 比内存构建与磁盘产物），不能只在 writeFile 那一侧做。
  const body = canonicalizeRegionPaths(chunk.code.trimEnd(), root);
  return [
    "// GENERATED by buildClient() in build-client.mjs — edit src/client-entry.ts, then run `node build-client.mjs`.",
    "window.__ModuleLoader__.load({",
    `  id: '${pkgName}',`,
    "  factory: (require) => {",
    "    var module = { exports: {} };",
    "    var exports = module.exports;",
    body,
    "    return module.exports;",
    "  },",
    "});",
    "",
  ].join("\n");
}

async function main() {
  const out = await buildClient();
  await writeFile(path.join(root, "client.js"), out, "utf8");
  console.info("client.js written:", out.length, "chars");
}

if (process.argv[1] === import.meta.filename) {
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}
