#!/usr/bin/env node
/// <reference types="node" />
// 构建 host.js：rolldown 把 host.ts 及其 `./src/*` 本地依赖打成单文件 ESM，落在**包根**
// （与源码同目录，故 `import.meta.dirname` 的语义与源码态完全一致）。
// 为什么必须有这一步：Node 对 node_modules 里的 .ts 直接抛
// ERR_UNSUPPORTED_NODE_MODULES_TYPE_STRIPPING（实测），而发布出去的包正是躺在
// node_modules 里被 dsh 载入的；官方示例包（docs/user/develop/basic/publish.zh.md
// 的 hello-plugin）也是包根放 index.js 产物。本仓 host.ts + client.js 同形态。
// 不产 .d.ts：插件包对外没有 TS API——dsh 按包名载入运行，没有人 import 它。
// 顶部 node reference：oxlint 类型检查对 .mjs 不自动加载 @types/node，需显式声明
// 才能解析 node:fs/promises、process、import.meta（否则整文件按 error 类型误报 unsafe）。
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { rolldown } from "rolldown";
import { canonicalizeRegionPaths } from "@jayyuen66/dsh-plugin-shared/lib/canonicalize-region-paths";

const root = import.meta.dirname;

/** @type {unknown} */
const pkgJson = JSON.parse(await readFile(path.join(root, "package.json"), "utf8"));

/**
 * 从 JSON.parse 的 unknown 投影为 Record（非对象 → 空对象兜底），避免 any 索引。
 * @param {unknown} raw
 * @returns {Record<string, unknown>}
 */
function asRecord(raw) {
  if (raw !== null && typeof raw === "object" && !Array.isArray(raw)) {
    return raw;
  }
  return {};
}

/**
 * 取依赖表里的包名清单（值即外部化说明符）。
 * @param {string} field
 * @returns {string[]}
 */
function dependencyNames(field) {
  const table = asRecord(asRecord(pkgJson)[field]);
  return Object.keys(table).filter((name) => typeof table[name] === "string");
}

// dependencies/peerDependencies 一律外部化：它们由 pnpm 真实安装，产物里保留裸
// 说明符才拿得到单例（内联会把 shared 的模块级状态复制成多份）。子路径说明符同样
// 要外部化——external 的字符串项是精确匹配，所以按「包名段」判定而不是枚举子路径。
const externalNames = new Set([
  ...dependencyNames("dependencies"),
  ...dependencyNames("peerDependencies"),
]);

/**
 * 说明符的包名段：`@scope/pkg/sub` → `@scope/pkg`，`pkg/sub` → `pkg`。
 * @param {string} id
 * @returns {string}
 */
function packageNameOf(id) {
  const segments = id.split("/");
  if (id.startsWith("@")) {
    return segments.slice(0, 2).join("/");
  }
  return segments[0] ?? id;
}

/**
 * rolldown 外部化判据。
 * @param {string} id
 * @returns {boolean}
 */
const isExternal = (id) => externalNames.has(packageNameOf(id));

/**
 * 本包的产物表：源码入口 → 落盘文件名。
 *
 * 为什么拆成两个产物：内置精选模板表（src/default-templates.generated.ts，生成物约 640 KB
 * 源码）原本被静态导入打进 host.js，于是**宿主载入插件的那一刻**这 85 条模板就已经占住内存，
 * 哪怕用户从不开「模板」下拉。改成独立产物后，host.ts 只在 default-templates 端点第一次
 * 被请求时 import 它——客户端那一侧本来就是按需拉的（走该端点），这一步只是把宿主侧对齐。
 *
 * 两个产物都必须落在**包根**（与 host.ts 同目录）：host.js 用 import.meta.dirname 定位
 * agents/，templates.data.mjs 用 import.meta.url 相对定位自己，落进 dist/ 两者都会静默失联。
 */
const ARTIFACTS = [
  {
    source: "host.ts",
    output: "host.js",
    header:
      "// GENERATED by build-host.mjs — edit host.ts / src/*.ts, then run `node build-host.mjs`.\n",
  },
  {
    source: "src/default-templates.generated.ts",
    output: "templates.data.mjs",
    header:
      "// GENERATED by build-host.mjs — edit src/default-templates.generated.ts (via scripts/gen-defaults.mjs), then run `node build-host.mjs`.\n",
  },
];

/**
 * 逐个产物跑一遍 rolldown，交回「落盘绝对路径 → 正文」。
 *
 * 返回 Map 而不是单串，是为了让 test/host-freshness.ts 的逐字节门禁把两个产物都算进去：
 * 它对 Map 形态会折成「相对路径 + 摘要」清单两侧比对，任一产物停在上一次构建都会红。
 *
 * @returns {Promise<Map<string, string>>}
 */
export async function buildHost() {
  // 两条产物互不依赖（各自的入口之间没有共享 chunk），并发跑即可；串行只是在等第二次
  // 构建，而 no-await-in-loop 也会因此报出来。
  const built = await Promise.all(
    ARTIFACTS.map(async (artifact) => {
      const bundle = await rolldown({
        input: path.join(root, artifact.source),
        external: isExternal,
        platform: "node",
        resolve: { extensions: [".ts", ".mjs", ".js"] },
      });
      const { output } = await bundle.generate({ format: "esm" });
      const chunk = output.find((item) => item.type === "chunk");
      if (chunk === undefined) {
        throw new Error(`rolldown generate returned no chunk output for ${artifact.source}`);
      }
      // `//#region` 行的路径由 rolldown 按 process.cwd() 算出 ⇒ 同一份源码有两种字节（cwd=包根 写
      // `lib/x.ts`，cwd=plugins/ 写 `<包名>/lib/x.ts`）。折成 canonical 必须落在**返回值之前**：
      // test/host-freshness.ts 拿内存构建与磁盘产物逐字节比，只在一侧折就永远红。
      const code = canonicalizeRegionPaths(chunk.code.trimEnd(), root);
      return [path.join(root, artifact.output), `${artifact.header}${code}\n`];
    }),
  );
  return new Map(built);
}

async function main() {
  const artifacts = await buildHost();
  await Promise.all([...artifacts].map(([file, code]) => writeFile(file, code, "utf8")));
  console.info(
    "written:",
    [...artifacts].map(([file, code]) => `${path.basename(file)} ${code.length} chars`).join(", "),
  );
}

if (process.argv[1] === import.meta.filename) {
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exitCode = 1;
  }
}
